nome = input("Digite seu nome completo: ")
print("Seu nome em maiúsculo é: {}".format(nome.upper()))
print("Seu nome em minúsculo é: {}".format(nome.lower()))
print("Seu nome tem {} letras".format(len(nome) - nome.count(" ")))
print("Seu primeiro nome é {}".format(nome.split()[0]))
